import type { SiteSettings, Project, Testimonial } from './types';

const imageById: Record<string, string> = {
  'hero-bg': 'https://picsum.photos/seed/404/1920/1080',
  'about-image': 'https://picsum.photos/seed/2/600/800',
  'project-1-cover': 'https://picsum.photos/seed/111/1200/800',
  'project-1-gallery-1': 'https://picsum.photos/seed/102/800/600',
  'project-1-gallery-2': 'https://picsum.photos/seed/103/800/600',
  'project-1-before': 'https://picsum.photos/seed/104/800/600',
  'project-1-after': 'https://picsum.photos/seed/105/800/600',
  'project-2-cover': 'https://picsum.photos/seed/201/1200/800',
  'project-2-gallery-1': 'https://picsum.photos/seed/202/800/600',
  'project-2-gallery-2': 'https://picsum.photos/seed/203/800/600',
  'project-2-before': 'https://picsum.photos/seed/204/800/600',
  'project-2-after': 'https://picsum.photos/seed/205/800/600',
  'project-3-cover': 'https://picsum.photos/seed/301/1200/800',
  'project-3-gallery-1': 'https://picsum.photos/seed/302/800/600',
  'project-3-gallery-2': 'https://picsum.photos/seed/303/800/600',
  'project-3-before': 'https://picsum.photos/seed/304/800/600',
  'project-3-after': 'https://picsum.photos/seed/305/800/600',
  'testimonial-avatar-1': 'https://picsum.photos/seed/901/100/100',
  'testimonial-avatar-2': 'https://picsum.photos/seed/902/100/100',
};

const getImage = (id: string) => imageById[id] || '';

export const siteSettings: SiteSettings = {
  title: 'sadique.co',
  tagline: 'Where your property finds its digital home.',
  contactEmail: 'hello@sadique.co',
  socialLinks: {
    twitter: 'https://x.com/notsadique',
    linkedin: 'https://www.linkedin.com/in/sadiqueh/',
    github: 'https://github.com/sadique-xo',
    dribbble: 'https://dribbble.com/designbysadique'
  },
};

export const projects: Project[] = [
  {
    id: '1',
    title: 'The Glass House',
    slug: 'the-glass-house',
    description: 'A full-fledged website design for a luxury villa, focusing on immersive visuals and a seamless booking experience. The design highlights the unique architectural features and stunning location.',
    shortDescription: 'Modern web presence for a luxury villa.',
    challenge: 'The Glass House had stunning architecture but relied solely on third-party booking sites with high commissions and no brand control. They needed a dedicated web presence to attract high-end clientele and manage direct bookings.',
    solution: 'We designed a visually-driven website with a minimalist aesthetic to let the property shine. We integrated a direct booking system, a professional gallery, and an interactive map. The site was built on Next.js for speed and SEO.',
    results: 'Within 3 months of launch, direct bookings increased by 40%, reducing commission costs significantly. The website now ranks on the first page for "luxury villa Malibu" and has become their primary marketing asset.',
    images: [getImage('project-1-gallery-1'), getImage('project-1-gallery-2')],
    coverImage: getImage('project-1-cover'),
    beforeImage: getImage('project-1-before'),
    afterImage: getImage('project-1-after'),
    tags: ['Web Design', 'Real Estate', 'Luxury', 'Booking Integration'],
    location: 'Malibu, California',
    published: true,
    createdAt: new Date('2023-05-15'),
    updatedAt: new Date('2023-05-20'),
  },
  {
    id: '2',
    title: 'Downtown Loft',
    slug: 'downtown-loft',
    description: 'A stylish and modern website for a chic downtown Airbnb loft. The project involved creating a brand identity and a mobile-first design to attract urban travelers.',
    shortDescription: 'Chic booking site for an urban Airbnb.',
    challenge: 'The client\'s stylish loft was lost in the sea of generic Airbnb listings. They struggled to convey the unique vibe and attract their ideal guest—the design-conscious urban traveler.',
    solution: 'We developed a strong brand identity and a mobile-first one-page website that felt like a digital magazine. High-quality visuals, neighborhood guides, and a clear call-to-action to book on Airbnb created a premium experience.',
    results: 'The new site led to a 25% increase in nightly rate and a feature on a popular travel blog. The client now attracts guests who appreciate the design and are willing to pay a premium.',
    images: [getImage('project-2-gallery-1'), getImage('project-2-gallery-2')],
    coverImage: getImage('project-2-cover'),
    beforeImage: getImage('project-2-before'),
    afterImage: getImage('project-2-after'),
    tags: ['Branding', 'Web Design', 'Airbnb', 'Mobile-First'],
    location: 'New York City, NY',
    published: true,
    createdAt: new Date('2023-08-01'),
    updatedAt: new Date('2023-08-10'),
  },
  {
    id: '3',
    title: 'Seaside Escape',
    slug: 'seaside-escape',
    description: 'A serene and elegant website for a beachfront property rental. The focus was on high-quality photography and a calming user interface to reflect the tranquil location.',
    shortDescription: 'Elegant rental site for a beachfront property.',
    challenge: 'A beautiful beachfront property was struggling with seasonal bookings. Their online presence was dated and didn\'t capture the serene, high-end experience they offered.',
    solution: 'We created an elegant, calming website using a soft color palette and large, immersive photos of the ocean. A simple inquiry form and an availability calendar made it easy for visitors to plan their stay.',
    results: 'Off-season inquiries increased by 60%. The average booking duration grew from 3 days to 7 days as the website effectively communicated the value of a longer, relaxing stay.',
    images: [getImage('project-3-gallery-1'), getImage('project-3-gallery-2')],
    coverImage: getImage('project-3-cover'),
    beforeImage: getImage('project-3-before'),
    afterImage: getImage('project-3-after'),
    tags: ['Web Design', 'Booking Platform', 'React', 'UI/UX'],
    location: 'The Hamptons, NY',
    published: true,
    createdAt: new Date('2023-11-22'),
    updatedAt: new Date('2023-11-28'),
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Anjali S.',
    role: 'EcoStay Owner',
    quote: 'Sadique transformed our Airbnb page into a stunning website that doubled our bookings in three months.',
    avatarUrl: getImage('testimonial-avatar-1'),
    sourceLink: '#',
    createdAt: new Date('2023-06-01'),
  },
  {
    id: '2',
    name: 'John Smith',
    role: 'Airbnb Superhost',
    quote: 'Working with them was a breeze. They delivered a stunning, fast, and easy-to-manage website that truly captures the essence of my property. I couldn\'t be happier with the result.',
    avatarUrl: getImage('testimonial-avatar-2'),
    createdAt: new Date('2023-09-15'),
  },
];
