"use client";

import { useState } from "react";
import Image from "next/image";
import { motion, AnimatePresence } from "framer-motion";
import { X, ExternalLink, Github, ArrowRight, Sparkles } from "lucide-react";
import { useTheme } from "next-themes";
import Breadcrumb from "@/components/Breadcrumb";
import { MagicCard } from "@/components/ui/magic-card";

// ── Tool Data ──────────────────────────────────────────────────────────
const tools = [
    {
        id: "cover-craft",
        title: "CoverCraft",
        tagline: "AI-powered cover letter generator",
        description:
            "Generate tailored, professional cover letters in seconds using AI. Paste your resume and a job description — CoverCraft handles the rest, crafting a compelling narrative that highlights your strengths.",
        image:
            "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&q=80",
        color: "from-violet-500/20 to-indigo-500/20",
        accent: "bg-violet-500",
        tags: ["AI", "Productivity", "Career"],
        link: "#",
        github: "#",
        status: "Live",
    },
    {
        id: "pixel-palette",
        title: "PixelPalette",
        tagline: "Smart color palette extraction from images",
        description:
            "Upload any image and instantly extract a harmonious color palette. PixelPalette uses advanced algorithms to identify dominant, complementary, and accent colors — perfect for designers and developers.",
        image:
            "https://images.unsplash.com/photo-1550859492-d5da9d8e45f3?w=800&q=80",
        color: "from-pink-500/20 to-rose-500/20",
        accent: "bg-pink-500",
        tags: ["Design", "Colors", "Utility"],
        link: "#",
        github: "#",
        status: "Live",
    },
    {
        id: "snap-og",
        title: "SnapOG",
        tagline: "Beautiful Open Graph image generator",
        description:
            "Create stunning OG images for your blog posts, projects, and social shares. Choose from templates, customize typography and gradients, and export pixel-perfect social cards instantly.",
        image:
            "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
        color: "from-amber-500/20 to-orange-500/20",
        accent: "bg-amber-500",
        tags: ["Social", "Marketing", "Design"],
        link: "#",
        github: "#",
        status: "Beta",
    },
    {
        id: "deploy-dash",
        title: "DeployDash",
        tagline: "Deployment status dashboard for teams",
        description:
            "Monitor all your deployments across Vercel, Netlify, and Railway in one unified dashboard. Real-time status updates, rollback controls, and team notifications — never miss a failed deploy again.",
        image:
            "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
        color: "from-emerald-500/20 to-teal-500/20",
        accent: "bg-emerald-500",
        tags: ["DevOps", "Dashboard", "Monitoring"],
        link: "#",
        github: "#",
        status: "Coming Soon",
    },
    {
        id: "font-forge",
        title: "FontForge",
        tagline: "Font pairing & preview tool for designers",
        description:
            "Find the perfect font combination for your next project. Preview Google Fonts pairings in real-time, adjust weights and sizes, and export CSS snippets — all in a beautifully minimal interface.",
        image:
            "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
        color: "from-cyan-500/20 to-blue-500/20",
        accent: "bg-cyan-500",
        tags: ["Typography", "Design", "CSS"],
        link: "#",
        github: "#",
        status: "Live",
    },
    {
        id: "readme-ai",
        title: "ReadmeAI",
        tagline: "Auto-generate beautiful README files",
        description:
            "Point it at any GitHub repo and get a polished, comprehensive README.md generated by AI. Includes badges, installation steps, API docs, and contribution guidelines — customizable to your style.",
        image:
            "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&q=80",
        color: "from-fuchsia-500/20 to-purple-500/20",
        accent: "bg-fuchsia-500",
        tags: ["AI", "GitHub", "Documentation"],
        link: "#",
        github: "#",
        status: "Beta",
    },
];

type Tool = (typeof tools)[number];

// ── Status Badge ────────────────────────────────────────────────────────
function StatusBadge({ status }: { status: string }) {
    const colors: Record<string, string> = {
        Live: "bg-emerald-500/15 text-emerald-400 border-emerald-500/20",
        Beta: "bg-amber-500/15 text-amber-400 border-amber-500/20",
        "Coming Soon": "bg-blue-500/15 text-blue-400 border-blue-500/20",
    };

    return (
        <span
            className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium border ${colors[status] || "bg-muted text-muted-foreground border-border"
                }`}
        >
            {status === "Live" && (
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
            )}
            {status}
        </span>
    );
}

// ── Tool Card ───────────────────────────────────────────────────────────
function ToolCard({
    tool,
    index,
    onClick,
}: {
    tool: Tool;
    index: number;
    onClick: () => void;
}) {
    const { theme } = useTheme();

    return (
        <motion.div
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{
                duration: 0.6,
                delay: index * 0.1,
                ease: [0.76, 0, 0.24, 1],
            }}
        >
            <MagicCard
                className="rounded-3xl cursor-pointer p-0"
                gradientColor={theme === "dark" ? "#262626" : "#D9D9D955"}
            >
                <motion.button
                    onClick={onClick}
                    className="group w-full text-left rounded-3xl overflow-hidden"
                    whileHover={{ y: -4 }}
                    whileTap={{ scale: 0.98 }}
                    transition={{ duration: 0.3 }}
                >
                    {/* Image */}
                    <div className="relative h-48 sm:h-56 overflow-hidden rounded-t-3xl">
                        <Image
                            src={tool.image}
                            alt={tool.title}
                            fill
                            className="object-cover transition-transform duration-700 group-hover:scale-110"
                            sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                        />
                        {/* Gradient overlay */}
                        <div
                            className={`absolute inset-0 bg-gradient-to-t ${tool.color} opacity-0 group-hover:opacity-100 transition-opacity duration-500`}
                        />
                        <div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-transparent" />

                        {/* Status */}
                        <div className="absolute top-4 left-4">
                            <StatusBadge status={tool.status} />
                        </div>

                        {/* Hover arrow */}
                        <div className="absolute bottom-4 right-4 w-10 h-10 rounded-full bg-white/10 dark:bg-white/5 backdrop-blur-md flex items-center justify-center border border-white/20 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                            <ArrowRight className="w-4 h-4 text-white group-hover:translate-x-0.5 transition-transform" />
                        </div>
                    </div>

                    {/* Content */}
                    <div className="p-6">
                        <h3 className="font-headline text-xl font-semibold text-foreground mb-1 group-hover:text-primary transition-colors duration-300">
                            {tool.title}
                        </h3>
                        <p className="text-sm text-muted-foreground mb-4">{tool.tagline}</p>

                        {/* Pill Tags */}
                        <div className="flex flex-wrap gap-2">
                            {tool.tags.map((tag) => (
                                <span
                                    key={tag}
                                    className="px-3 py-1 rounded-full text-xs font-medium bg-foreground/[0.06] dark:bg-muted/30 text-foreground/60 dark:text-muted-foreground border border-foreground/[0.08] dark:border-border/20"
                                >
                                    {tag}
                                </span>
                            ))}
                        </div>
                    </div>

                    {/* Bottom accent line */}
                    <div
                        className={`absolute bottom-0 left-0 right-0 h-0.5 ${tool.accent} opacity-0 group-hover:opacity-100 transition-opacity duration-500`}
                    />
                </motion.button>
            </MagicCard>
        </motion.div>
    );
}

// ── Drawer ───────────────────────────────────────────────────────────────
function ToolDrawer({
    tool,
    onClose,
}: {
    tool: Tool | null;
    onClose: () => void;
}) {
    return (
        <AnimatePresence>
            {tool && (
                <>
                    {/* Backdrop */}
                    <motion.div
                        className="fixed inset-0 z-[70] bg-black/60 backdrop-blur-sm"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        transition={{ duration: 0.3 }}
                        onClick={onClose}
                    />

                    {/* Drawer */}
                    <motion.div
                        className="fixed top-0 right-0 bottom-0 z-[80] w-full sm:w-[680px] md:w-[780px] bg-background border-l border-border/50 rounded-l-3xl shadow-2xl flex flex-col overflow-hidden"
                        initial={{ x: "100%" }}
                        animate={{ x: 0 }}
                        exit={{ x: "100%" }}
                        transition={{ duration: 0.5, ease: [0.76, 0, 0.24, 1] as const }}
                    >
                        {/* Close button */}
                        <div className="absolute top-4 left-4 z-10">
                            <motion.button
                                onClick={onClose}
                                className="w-10 h-10 rounded-full bg-white/20 dark:bg-black/30 backdrop-blur-xl flex items-center justify-center border border-white/30 dark:border-white/10 shadow-lg hover:bg-white/30 dark:hover:bg-black/40 transition-colors"
                                whileHover={{ scale: 1.1, rotate: 90 }}
                                whileTap={{ scale: 0.9 }}
                            >
                                <X className="w-4 h-4 text-white drop-shadow-md" />
                            </motion.button>
                        </div>

                        {/* Scrollable content */}
                        <div className="flex-1 overflow-y-auto">
                            {/* Hero Image */}
                            <div className="relative h-64 sm:h-80">
                                <Image
                                    src={tool.image}
                                    alt={tool.title}
                                    fill
                                    className="object-cover"
                                    sizes="600px"
                                />
                                <div
                                    className={`absolute inset-0 bg-gradient-to-t ${tool.color} mix-blend-multiply`}
                                />
                                <div className="absolute inset-0 bg-gradient-to-t from-background via-background/40 to-transparent" />

                                {/* Title overlay */}
                                <div className="absolute bottom-6 left-6 right-6">
                                    <motion.div
                                        initial={{ opacity: 0, y: 20 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        transition={{ delay: 0.2, duration: 0.5 }}
                                    >
                                        <StatusBadge status={tool.status} />
                                        <h2 className="font-headline text-3xl sm:text-4xl font-bold text-foreground mt-3">
                                            {tool.title}
                                        </h2>
                                        <p className="text-muted-foreground mt-1">{tool.tagline}</p>
                                    </motion.div>
                                </div>
                            </div>

                            {/* Body */}
                            <div className="p-6 sm:p-8 space-y-8">
                                {/* Description */}
                                <motion.div
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: 0.3, duration: 0.5 }}
                                >
                                    <h3 className="text-sm font-mono uppercase tracking-widest text-muted-foreground mb-3">
                                        About
                                    </h3>
                                    <p className="text-foreground/80 leading-relaxed text-base">
                                        {tool.description}
                                    </p>
                                </motion.div>

                                {/* Tags */}
                                <motion.div
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: 0.4, duration: 0.5 }}
                                >
                                    <h3 className="text-sm font-mono uppercase tracking-widest text-muted-foreground mb-3">
                                        Stack
                                    </h3>
                                    <div className="flex flex-wrap gap-2">
                                        {tool.tags.map((tag, i) => (
                                            <motion.span
                                                key={tag}
                                                className="px-4 py-1.5 rounded-full text-sm font-medium bg-foreground/[0.06] dark:bg-muted/30 text-foreground/60 dark:text-foreground/70 border border-foreground/[0.08] dark:border-border/20"
                                                initial={{ opacity: 0, scale: 0.8 }}
                                                animate={{ opacity: 1, scale: 1 }}
                                                transition={{ delay: 0.4 + i * 0.05 }}
                                            >
                                                {tag}
                                            </motion.span>
                                        ))}
                                    </div>
                                </motion.div>

                                {/* Links */}
                                <motion.div
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: 0.5, duration: 0.5 }}
                                    className="flex flex-col sm:flex-row gap-3"
                                >
                                    <a
                                        href={tool.link}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="flex-1 flex items-center justify-center gap-2 px-6 py-3.5 rounded-2xl bg-primary text-primary-foreground font-medium hover:opacity-90 transition-opacity"
                                    >
                                        <ExternalLink className="w-4 h-4" />
                                        Visit Tool
                                    </a>
                                    <a
                                        href={tool.github}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="flex-1 flex items-center justify-center gap-2 px-6 py-3.5 rounded-2xl bg-muted text-foreground font-medium border border-border/50 hover:bg-muted/80 transition-colors"
                                    >
                                        <Github className="w-4 h-4" />
                                        Source Code
                                    </a>
                                </motion.div>
                            </div>
                        </div>
                    </motion.div>
                </>
            )}
        </AnimatePresence>
    );
}

// ── Page ─────────────────────────────────────────────────────────────────
export default function ToolsPage() {
    const [selectedTool, setSelectedTool] = useState<Tool | null>(null);

    return (
        <div className="bg-background min-h-screen">
            <div className="container mx-auto px-4 py-16 md:py-24">
                <div className="max-w-6xl mx-auto">
                    <Breadcrumb items={[{ label: "Tools I Build" }]} className="mb-8" />

                    {/* Header */}
                    <motion.header
                        className="mb-16"
                        initial={{ opacity: 0, y: 30 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6 }}
                    >
                        <div className="flex items-center gap-3 mb-4">
                            <div className="p-2 rounded-xl bg-primary/10">
                                <Sparkles className="w-5 h-5 text-primary" />
                            </div>
                            <span className="text-sm font-mono uppercase tracking-widest text-muted-foreground">
                                Side Projects & Experiments
                            </span>
                        </div>
                        <h1 className="font-headline text-4xl font-bold text-foreground md:text-6xl mb-6">
                            Tools I Build
                        </h1>
                        <p className="text-xl text-muted-foreground max-w-2xl">
                            A collection of tools, experiments, and side projects I&apos;ve
                            built to solve real problems and explore new ideas.
                        </p>
                    </motion.header>

                    {/* Grid */}
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {tools.map((tool, index) => (
                            <ToolCard
                                key={tool.id}
                                tool={tool}
                                index={index}
                                onClick={() => setSelectedTool(tool)}
                            />
                        ))}
                    </div>
                </div>
            </div>

            {/* Drawer */}
            <ToolDrawer
                tool={selectedTool}
                onClose={() => setSelectedTool(null)}
            />
        </div>
    );
}
